### PR TITLE
Improve structure, formatting and wording

### PR DESCRIPTION
**Pull request by piotrowski**
- Method descriptions as headline to add structure
- Small formatting changes for the ENUM values
- Small wording changes to improve clarity
- Link to cordova-config-utils

### CODE REVIEW

**Comment by peutetre** [comment]
@piotrowski, can you update your PR, so that I can test and release 2.1.0

**Comment by piotrowski** [comment]
Hm? I think you want me to include the changes that happened on master... but to be honest I have no idea how to do that. Normally I just edit files in the online editor here.

Is there a way to "rebase" in the web UI of Github? Otherwise I will have to create a new PR and 'redo' my changes on the current version.

**Comment by piotrowski** [comment]
Found it: http://www.hpique.com/2013/09/updating-a-fork-directly-from-github/

**Comment by piotrowski** [comment]
Yay, I think I did it! It's not pretty as of course I had to manually fix a conflict (Github for Windows is shit. Luckily Sourcetree could help. More or less...) but I think I also fixed that one and didn't loose or break anything.

Right?

**Comment by peutetre** [comment]
looks good thanks!

**Pull request merged**
