### PR TITLE
Various functionality additions/improvements

### PR DESCRIPTION
**Pull request by dlevine82**
- Adds ability to include additional metadata with crash reporting
- Adds ability to specify non-anonymous login modes
- Some code clean-up

### CODE REVIEW

**Comment by piotrowski** [comment]
Looks nice!

**Comment by peutetre** [comment]
looks very nice!
as @piotrowski mentioned, the readme needs to be upgraded. After testing, I will release a new major version.
thanks @dlevine82

**Comment by dlevine82** [comment]
Thanks, guys! README has been updated.

**Comment by peutetre** [comment]
Tanks to you (and all commiters from Microsoft)!

**Comment by lostintangent** [comment]
@peutetre How did the testing go? I'm excited to get these changes merged in :)

We're planning to start producing more HockeApp/Cordova guidance and plan to prescribe your awesome plugin!

**Comment by peutetre** [comment]
cordova-plugin-hockeyapp@2.0.0 is published on npm and tested (https://github.com/peutetre/example-cordova-plugin-hockeyapp)

btw. the new `addMetaData()` is really nice!

screen shot 2016-01-11 at 20 09 39
screen shot 2016-01-11 at 20 11 00

**Pull request merged**
